# Lobby
execute @e[type=sfx:execute,scores={sb=0}] ~~~ titleraw @a title {"rawtext":[{"text":"   §l§7Vortex §fNetwork§r\n\n §rType:§7 UHC\n §rMode: §7TO"},{"score":{"name":"@e[type=sfx:execute]","objective":"teamax"}},{"text":"\n §rHost: §7"},{"selector":"@a[tag=host]"},{"text":"§7\n\n --Waiting Players--\n §8dsc.gg/vortexuhc§r\n"}]}

execute @e[type=sfx:execute,scores={sb=1}] ~~~ titleraw @a title {"rawtext":[{"text":"   §l§7Vortex §fNetwork§r\n\n §rType:§7 UHC\n §rMode: §7FFA\n §rHost: §7"},{"selector":"@a[tag=host]"},{"text":"§7\n\n --Waiting Players--\n §8dsc.gg/vortexuhc§r\n"}]}

# Ingame
execute @e[type=sfx:execute,scores={sb=2}] ~~~ execute @a ~~~ titleraw @s title {"rawtext":[{"text":"   §l§7Vortex §fNetwork§r\n\n Time: §7"},{"score":{"name":"@e[type=sfx:execute]","objective":"h"}},{"text":":"},{"score":{"name":"@e[type=sfx:execute]","objective":"m"}},{"text":":"},{"score":{"name":"@e[type=sfx:execute]","objective":"s"}},{"text":"\n§r\n Your Kills: §7"},{"score":{"name":"@s","objective":"kill"}},{"text":"§r\n\n Players Left: §7"},{"score":{"name":"live","objective":"live"}},{"text":"§r\n Border: §7"},{"score":{"name":"borde","objective":"border"}},{"text":"§r\n\n §8dsc.gg/vortexuhc§r\n"}]}

# Winner
execute @e[type=sfx:execute,scores={sb=3}] ~~~ execute @a ~~~ titleraw @s title {"rawtext":[{"text":"   §l§7Vortex §fNetwork§r\n\n Time: §7"},{"score":{"name":"@e[type=sfx:execute]","objective":"h"}},{"text":":"},{"score":{"name":"@e[type=sfx:execute]","objective":"m"}},{"text":":"},{"score":{"name":"@e[type=sfx:execute]","objective":"s"}},{"text":"\n§r\n Your Kills: §7"},{"score":{"name":"@s","objective":"kill"}},{"text":"§r\n\n Winner: §e"},{"selector":"@a[tag=win]"},{"text":"§r\n Winner Kills: §e"},{"score":{"name":"@a[tag=win]","objective":"kill"}},{"text":"§r\n\n §8dsc.gg/vortexuhc§r\n"}]}