execute @s[scores={de=1}] ~~~ playsound uhc.boom @a
execute @s[scores={de=2}] ~~~ playsound uhc.taco @a
execute @s[scores={de=3}] ~~~ playsound uhc.sp @a
execute @s[scores={de=4}] ~~~ playsound uhc.peo @a
execute @s[scores={de=5}] ~~~ playsound uhc.critico @a
execute @s[scores={de=6}] ~~~ playsound uhc.sus @a
execute @s[scores={de=7}] ~~~ playsound uhc.oof @a
execute @s[scores={de=8}] ~~~ playsound uhc.o @a
execute @s[scores={de=9}] ~~~ playsound uhc.bruh @a
execute @s[scores={de=10}] ~~~ playsound uhc.dross @a
execute @s[scores={de=11}] ~~~ playsound uhc.l @a
execute @s[scores={de=12}] ~~~ playsound uhc.yo @a
execute @s[scores={de=13}] ~~~ playsound uhc.w @a
execute @s[scores={de=14}] ~~~ playsound uhc.omg @a
execute @s[scores={de=15}] ~~~ playsound uhc.white @a
execute @s[scores={de=16}] ~~~ playsound uhc.hola @a